config/routes.rb
Rails.application.routes.draw do

 resources :students, only: [:new, :create, :index, :show, :destroy] do
    resources :steps, only: [:show, :update], controller: 'student/steps'
  end

  resources :employees, only: [:new, :create, :index, :show, :destroy] do
    resources :steps, only: [:show, :update], controller: 'employee/steps'
  end


  root to: 'employees#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
   extend FriendlyId
    friendly_id :name, use: :slugged
    
	  cattr_accessor :form_steps do
    %w(identity characteristics instructions)
  end

  attr_accessor :form_step

  validates :first_name,:department, presence: true, if: -> { required_for_step?(:identity) }
  validates :phone_no,:city, presence: true, if: -> { required_for_step?(:characteristics) }
  validates :adharcard, presence: true, if: -> { required_for_step?(:instructions) }

  def required_for_step?(step)
    return true if form_step.nil?
    return true if self.form_steps.index(step.to_s) <= self.form_steps.index(form_step)
  end


def self.search(employee)
  if employee
    where('employee_id or first_name or last_name or phone_no or job_title or department or address_line1  LIKE ?', "%#{employee}%").order('id DESC')
  else
    order('id DESC') 
  end
end

  mount_uploader :photo, PhotoUploader
  mount_uploader :adharcard, PhotoUploader
  mount_uploader :pan_card, PhotoUploader
  mount_uploader :voter_card, PhotoUploader
  mount_uploader :passport, PhotoUploader
  mount_uploader :last_degree, PhotoUploader
  mount_uploader :experience_certificate, PhotoUploader

def name
    "#{self.first_name} #{self.last_name}"
  end

end

app/models/student.rb
class Student < ApplicationRecord
   extend FriendlyId
    friendly_id :name, use: :slugged
    
	  cattr_accessor :form_steps do
    %w(identity characteristics instructions)
  end

  attr_accessor :form_step

  validates :first_name,:address_line2, presence: true, if: -> { required_for_step?(:identity) }
  validates :father_name, presence: true, if: -> { required_for_step?(:characteristics) }
  validates :adharcard, presence: true, if: -> { required_for_step?(:instructions) }

  def required_for_step?(step)
    return true if form_step.nil?
    return true if self.form_steps.index(step.to_s) <= self.form_steps.index(form_step)
  end

def self.search(student)
  if student
    where('student_id or first_name or last_name or previous_school_name or phone_no  LIKE ?', "%#{student}%").order('id DESC')
  else
    order('id DESC') 
  end
end
  mount_uploader :photo, PhotoUploader
  mount_uploader :adharcard, PhotoUploader
   mount_uploader :previous_school_marksheet, PhotoUploader

def name
    "#{self.first_name} #{self.last_name}"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employee/steps_controller.rb
class Employee::StepsController < ApplicationController
  include Wicked::Wizard
  steps *Employee.form_steps

  def show
    @employee = Employee.find(params[:employee_id])
    render_wizard
  end

  def update
    @employee = Employee.find(params[:employee_id])
    @employee.update(employee_params(step))
    render_wizard @employee
  end

  private

  def employee_params(step)
    permitted_attributes = case step
                           when "identity"
                             [:joining_date, :first_name,:last_name,:dob, :gender, :department, :position,:job_title, :qualification, :experience, :maritel_status, :notification, :father_name, :mother_name, :blood_group, :spocecom,:photo]
                           when "characteristics"
                             [:address_line1, :address_line2,:city, :state, :pincode, :phone_no, :email]
                           when "instructions"
                             [:adharcard, :pan_card, :passport, :last_degree, :experience_certificate, :voter_card]
                           end

    params.require(:employee).permit(permitted_attributes).merge(form_step: step)
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.where.not(first_name: nil)
     # @employees = Employee.search(params[:employee])
        @q = Employee.ransack(params[:q])
    @employees = @q.result

  end

 
   def show
 @employee = Employee.friendly.find(params[:id])
  end


  def new
  	@employee = Employee.new
  end

  
  def create
  	@employee = Employee.new(employee_params)
  	@employee.save(validate: false)
  	redirect_to employee_step_path(@employee, Employee.form_steps.first)
  end

  def destroy
      @employee = Employee.friendly.find(params[:id])
        @employee.destroy
        redirect_to employees_path
  end

  private
    def employee_params
    	params.require(:employee).permit(:employee_id,:joining_date, :first_name,:last_name,:dob, :gender, :department, :position,:job_title, :qualification, :experience, :maritel_status, :qualification, :father_name, :mother_name, :blood_group, :spocecom,:photo,:address_line1, :address_line2,:city, :state, :pincode, :phone_no, :email,:adharcard, :pan_card, :passport, :last_degree, :experience_certificate, :voter_card)
    end
end

app/controllers/student/steps_controller.rb
class Student::StepsController < ApplicationController
  include Wicked::Wizard
  steps *Student.form_steps

  def show
    @student = Student.find(params[:student_id])
    render_wizard
  end

  def update
    @student = Student.find(params[:student_id])
    @student.update(student_params(step))
    render_wizard @student
  end

  private

  def student_params(step)
    permitted_attributes = case step
                           when "identity"
                             [:first_name, :last_name,:dob, :addmission_date, :gender, :blood_group, :birth_place,:student_class, :category,:session, :address_line1, :address_line2, :city, :state, :pincode, :phone_no, :photo]
                           when "characteristics"
                             [:father_name, :dob,:ocupasion, :income, :mother_name, :address_line1, :address_line2, :city, :state, :pincode, :phone_no, :emergency_no]
                           when "instructions"
                             [:previous_school_name, :obtained, :previous_class, :adharcard, :previous_school_marksheet]
                           end

    params.require(:student).permit(permitted_attributes).merge(form_step: step)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.where.not(Firstname: nil)
    # @students = Student.search(params[:student])
    @students = Student.order('addmission_date')
      @q = Student.ransack(params[:q])
    @students = @q.result

  end

 
  def show
    @student = Student.friendly.find(params[:id])
  end


  def new
  	@student = Student.new
  end


  def create
  	@student = Student.new(student_params)
  	@student.save(validate: false)
  	redirect_to student_step_path(@student, Student.form_steps.first)
  end


  def destroy
      @student = Student.friendly.find(params[:id])
        @student.destroy
        redirect_to students_path
  end

  private
    def student_params
    	params.require(:student).permit(:student_id,:first_name, :last_name, :dob, :gender, :blood_group, :birth_place, :Category,:student_class, :session, :address_line1, :address_line2, :city, :state, :pincode, :phone_no, :photo, :father_name,
    		:mother_name,:ocupasion, :income,:emergency_no,:previous_school_name, :obtained, :previous_class, :adharcard, :previous_school_marksheet, :addmission_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def show_errors(object, field_name)
  if object.errors.any?
    if !object.errors.messages[field_name].blank?
      object.errors.messages[field_name].join(", ")
    end
  end
end 
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/employee/steps/characteristics.html.erb
  <div id='wrapper'>
    <!-- Sidebar -->
    <section id='sidebar'>
      <i class='icon-align-justify icon-large' id='toggle'></i>
      <ul id='dock'>
        <li class='launcher'>
          <i class='icon-dashboard'></i>
          <a href="dashboard.html">Dashboard</a>
        </li>
        <li class='active launcher'>
          <i class="icofont icofont-user-male"></i>
          <a><%= link_to 'Addmission',
            new_employee_path %></a>
          </li>
          <li class='launcher'>
            <i class='icon-table'></i>
            <a ><%= link_to 'Tables',
              employees_path %></a>
            </li>
            <li class='launcher dropdown hover'>
              <i class='icon-flag'></i>
              <a href='#'>Reports</a>
              <ul class='dropdown-menu'>
                <li class='dropdown-header'>Launcher description</li>
                <li>
                  <a href='#'>Action</a>
                </li>
                <li>
                  <a href='#'>Another action</a>
                </li>
                <li>
                  <a href='#'>Something else here</a>
                </li>
              </ul>
            </li>
            <li class='launcher'>
              <i class='icon-bookmark'></i>
              <a href='#'>Bookmarks</a>
            </li>
            <li class='launcher'>
              <i class='icon-cloud'></i>
              <a href='#'>Backup</a>
            </li>
            <li class='launcher'>
              <i class='icon-bug'></i>
              <a href='#'>Feedback</a>
            </li>
          </ul>
          <div data-toggle='tooltip' id='beaker' title='Made by lab2023'></div>
        </section>
        <!-- Tools -->
        <section id='tools'>
          <ul class='breadcrumb' id='breadcrumb' style="background-color: #2c3e50; color: white">
            <li class='title'>Forms</li>
          </ul>
          <div id='toolbar'>

          </div>
        </section>
        <!-- Content -->
        <div id='content' style="background-color: #bdc3c7;">
          <div class='panel panel-default'>
            <div class='panel-heading' style="background-color: #2c3e50; color: white">
              <i class='icon-edit icon-large'></i>
              Employee
            </div>
            <div class='panel-body' style="background-color: #2c3e50; color: white">
             <%= form_for @employee, method: :put, url: wizard_path do |f| %>
            

            <fieldset>
              <div class="col-lg-6 left">
<center>
  
<i class="icofont icofont-architecture-alt"  style="font-size: 100px; "></i><br>
</center>
              <div class="form-group">
                <%= f.label :Address_Line1%><br>
                <%= f.text_field :address_line1, :class => 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :Address_Line2%><br>
                <%= f.text_field :address_line2, :class => 'form-control' %>
              </div class="form-group">
              <div>
                <%= f.label :City%><br>
                <%= f.text_field :city, :class => 'form-control' %>
                 <p class='error'><%= show_errors(@employee, :city) %></p>
              </div>
              <div class="form-group">
                <%= f.label :State%><br>
                <%= f.text_field :state, :class => 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :Pincode%><br>
                <%= f.text_field :pincode, :class => 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :Phone_Number%><br>
                <%= f.text_field :phone_no, :class => 'form-control' %>
                <p class='error'><%= show_errors(@employee, :phone_no) %></p>
              </div>
              <div class="form-group">
                <%= f.label :Email%><br>
                <%= f.text_field :email, :class => 'form-control' %>
              </div>

              <div>
                <%= f.submit 'Submit', :class => 'btn btn-success both' %>
              </div>
            </fieldset>
            <% end %>


          </div>
        </div>
        <div class='panel panel-default'>
          <div class='panel-heading' style="background-color: #2c3e50; color: white">
            <i class='icon-edit icon-large'></i>
            <!--  Knob Inputs -->
          </div>
        </div>
      </div>
    </div>
    <!-- Footer -->
    <!-- Javascripts -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script><script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" type="text/javascript"></script><script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js" type="text/javascript"></script><script src="assets/javascripts/application-985b892b.js" type="text/javascript"></script>
    <!-- Google Analytics -->
    <script>
      var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
      </script>
      <style type="text/css">
    

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
            <div id='wrapper'>
              <!-- Sidebar -->
              <section id='sidebar'>
                <i class='icon-align-justify icon-large' id='toggle'></i>
                <ul id='dock'>
                  <li class='launcher'>
                    <i class='icon-dashboard'></i>
                    <a href="dashboard.html">Dashboard</a>
                </li>
                <li class='launcher'>
                 <i class="icofont icofont-user-male"></i>
                 <a><%= link_to 'Addmission',
                    new_employee_path %></a>
                </li>
                <li class='active launcher'>
                    <i class='icon-table'></i>
                    <a href="tables.html"><%= link_to 'Tables',
                      employees_path %></a>
                  </li>
                  <li class='launcher dropdown hover'>
                      <i class='icon-flag'></i>
                      <a href='#'>Reports</a>
                      <ul class='dropdown-menu'>
                        <li class='dropdown-header'>Launcher description</li>
                        <li>
                          <a href='#'>Action</a>
                      </li>
                      <li>
                          <a href='#'>Another action</a>
                      </li>
                      <li>
                          <a href='#'>Something else here</a>
                      </li>
                  </ul>
              </li>
              <li class='launcher'>
                  <i class='icon-bookmark'></i>
                  <a href='#'>Bookmarks</a>
              </li>
              <li class='launcher'>
                  <i class='icon-cloud'></i>
                  <a href='#'>Backup</a>
              </li>
              <li class='launcher'>
                  <i class='icon-bug'></i>
                  <a href='#'>Feedback</a>
              </li>
          </ul>
          <div data-toggle='tooltip' id='beaker' title='Made by lab2023'></div>
      </section>
      <!-- Tools -->
      <section id='tools'>
          <ul class='breadcrumb' id='breadcrumb' style="background-color: #2c3e50">
            <li class='title'>Tables</li>
        </ul>
        <div id='toolbar'>
            <div class='btn-group'>
              <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Building'>
                <i class='icon-building'></i>
            </a>
            <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Laptop'>
                <i class='icon-laptop'></i>
            </a>
            <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Calendar'>
                <i class='icon-calendar'></i>
                <span class='badge'>3</span>
            </a>
            <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Lemon'>
                <i class='icon-lemon'></i>
            </a>
        </div>
    </div>
</section>
<!-- Content -->
<div id='content' style="background-color: #bdc3c7">
  <div class='panel panel-default grid'>
       <div class='panel-heading' style="background-color: #2c3e50; color: white">
        <i class='icon-table icon-large'></i>
        Employee Table
            <i class="icofont icofont-group-students icon" style="font-size: 30px;">

      </i>
      <%= link_to 'Student Table',
      students_path, :class => 'colors' %>
        <div class='panel-tools' >
          <div class='btn-group' >
            <a class='btn' href='#' style="color: white">
              <i class='icon-wrench'></i>
              Settings
          </a>
          <a class='btn' href='#' style="color: white">
              <i class='icon-filter'></i>
              Filters
          </a>
          <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Reload'>
              <i class='icon-refresh' style="color: white"></i>
          </a>
      </div>
      <div class='badge' style="color: white">3 record</div>
  </div>
</div>
<div class='panel-body filters' >
    <div class='row' >
      <div class='col-md-9' >
         <label style="text-align: center;">Date:
           <%= Time.now.strftime("%d/%m/%Y") %></label>
       </div>
       <div class='col-md-3'>
        <div class='input-group'>
          <%= search_form_for @q do |f| %>
          <%= f.label :name_cont %>
          <%= f.search_field :first_name_or_last_name_cont %>
          <%= f.submit %>
          <% end %>
      </div>
  </div>
</div>
</div>
<table class='table'>
    <thead>
      <tr style="background-color: #2c3e50; color: white">
        <th> photo</th>
        <th><%= sort_link(@q, :name)  %></th>
        <th><%= sort_link(@q, :dob)  %></th>
        <th><%= sort_link(@q, :job_title)  %></th>
        <th>Show Details</th>
        <th>Delete</th></tr>
    </thead>
    <tbody>
        <tr class='success'>
           <% @employees.each do |employee| %>
           <td><%= image_tag employee.photo, :class =>'img-responsive abc' %></td>
           <td><%= employee.name %></td>
           <td><%= employee.dob %></td>
           <td><%= employee.job_title %></td>
           <td><%= link_to '', employee_path(employee), :class => "fa fa-eye color"%></td>

           <td>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_path(employee),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-xs btn-danger' %>
          </td>
      </tr>
      <%end%>
  </tbody>
</table>
<div class='panel-footer' style="background-color: #2c3e50;" >
    <ul class='pagination pagination-sm'>
      <li>
        <a href='#'>«</a>
    </li>
    <li class='active'>
        <a href='#'>1</a>
    </li>
    <li>
        <a href='#'>2</a>
    </li>
    <li>
        <a href='#'>3</a>
    </li>
    <li>
        <a href='#'>4</a>
    </li>
    <li>
        <a href='#'>5</a>
    </li>
    <li>
        <a href='#'>6</a>
    </li>
    <li>
        <a href='#'>7</a>
    </li>
    <li>
        <a href='#'>8</a>
    </li>
    <li>
        <a href='#'>»</a>
    </li>
</ul>
<div class='pull-right' style="color: white">
  Showing 1 to 10 of 32 entries
</div>
</div>
</div>
</div>
</div>

<!-- Footer -->
<!-- Javascripts -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script><script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" type="text/javascript"></script><script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js" type="text/javascript"></script><script src="assets/javascripts/application-985b892b.js" type="text/javascript"></script>
<!-- Google Analytics -->
<script>
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

app/views/employees/new.html.erb
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta content='lab2023' name='author'>
  <meta content='' name='description'>
  <meta content='' name='keywords'>
  <meta charset='utf-8'>
  <meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="assets/stylesheets/application-a07755f5.css" rel="stylesheet" type="text/css" /><link href="//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="assets/images/favicon.ico" rel="icon" type="image/ico" />

  <title><%= content_for?(:title) ? yield(:title) : "Addmission" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>


  <%= javascript_include_tag "application" %>

</head>
<body class='main page'>
</div>
</div>
<div class="container">
  <div class="row">
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
 </div>
</div>

<%= bootstrap_flash %>
<%= yield %>


</div><!--/row-->
<footer>
  <p>&copy; Company 2018</p>
</footer>
</div> <!-- /container -->
</body>
</html>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
    <div id='wrapper' >
      <!-- Sidebar -->
      <section id='sidebar'>
        <i class='icon-align-justify icon-large' id='toggle'></i>
        <ul id='dock'>
          <li class='launcher'>
            <i class='icon-dashboard'></i>
            <a href="dashboard.html">Dashboard</a>
          </li>
          <li class='launcher'>
            <i class="icofont icofont-user-male"></i>
            <a><%= link_to 'Addmission',
              new_student_path %></a>

            </li>
            <li class='active launcher'>
              <i class='icon-table'></i>
              <a href="tables.html"><%= link_to 'Tables',
                students_path %></a>
              </li>
              <li class='launcher dropdown hover'>
                <i class='icon-flag'></i>
                <a href='#'>Reports</a>
                <ul class='dropdown-menu'>
                  <li class='dropdown-header'>Launcher description</li>
                  <li>
                    <a href='#'>Action</a>
                  </li>
                  <li>
                    <a href='#'>Another action</a>
                  </li>
                  <li>
                    <a href='#'>Something else here</a>
                  </li>
                </ul>
              </li>
              <li class='launcher'>
                <i class='icon-bookmark'></i>
                <a href='#'>Bookmarks</a>
              </li>
              <li class='launcher'>
                <i class='icon-cloud'></i>
                <a href='#'>Backup</a>
              </li>
              <li class='launcher'>
                <i class='icon-bug'></i>
                <a href='#'>Feedback</a>
              </li>
            </ul>
            <div data-toggle='tooltip' id='beaker' title='Made by lab2023'></div>
          </section>
          <!-- Tools -->
          <section id='tools'>
            <ul class='breadcrumb' id='breadcrumb' style="background-color: #2c3e50; color: white">
              <li class='title'>Tables</li>
            </ul>
            <div id='toolbar'>
              <div class='btn-group'>
                <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Building'>
                  <i class='icon-building'></i>
                </a>
                <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Laptop'>
                  <i class='icon-laptop'></i>
                </a>
                <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Calendar'>
                  <i class='icon-calendar'></i>
                  <span class='badge'>3</span>
                </a>
                <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Lemon'>
                  <i class='icon-lemon'></i>
                </a>
              </div>
            </div>
          </section>
          <!-- Content -->
          <div id='content' style="background-color: #bdc3c7;">
            <div class='panel panel-default grid'>
              <div class='panel-heading' style="background-color: #2c3e50; color: white">
                <i class='icon-table icon-large'></i>
                Student Table
                    <i class="icofont icofont-architecture-alt icon" style="font-size: 30px;">

      </i>
      <%= link_to 'Employee Table',
      employees_path, :class => 'colors' %>
                <div class='panel-tools'>
                  <div class='btn-group'>
                    <a class='btn' href='#' style="color: white">
                      <i class='icon-wrench'></i>
                      Settings
                    </a>
                    <a class='btn' href='#' style="color: white">
                      <i class='icon-filter'></i>
                      Filters
                    </a>
                    <a class='btn' data-toggle='toolbar-tooltip' href='#' title='Reload'>
                      <i class='icon-refresh'></i>
                    </a>
                  </div>
                  <div class='badge'>3 record</div>
                </div>
              </div>
              <div class='panel-body filters'>
                <div class='row'>
                  <div class='col-md-9'>
                   <label style="text-align: center;">Date:
                     <%= Time.now.strftime("%d/%m/%Y") %></label>
                   </div>
                   <div class='col-md-3'>
                     <div class='input-group'>
                      <%= search_form_for @q do |f| %>
                      <%= f.label :name_cont %>
                      <%= f.search_field :first_name_or_last_name_cont %>
                      <%= f.submit %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <table class='table'>
                <thead>
                  <tr style="background-color: #2c3e50; color: white">

                    <th>Photo</th>
                    <th><%= sort_link(@q, :name)  %></th>
                    <th><%= sort_link(@q, :dob)  %></th>
                    <th><%= sort_link(@q, :gender)  %></th>
                    <th><%= sort_link(@q, :phone_no)  %></th>
                    <th>Show Detail</th>
                    <th>Delete</th>
                  </tr>
                </thead>
                <tbody>
                  <tr class='success'>
                   <% @students.each do |student| %>
                   <td><%= image_tag student.photo, :class =>'img-responsive abc' %></td>

                   <td><%= student.name %></td>

                   <td><%= student.dob %></td>

                   <td><%= student.gender %></td>
                   <td><%= student.phone_no %></td>

                   <td><%= link_to '', student_path(student), :class => "fa fa-eye color"%></td>
                   <td>

                    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    student_path(student),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-xs btn-danger' %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <div class='panel-footer' style="background-color: #2c3e50; color: white">
              <ul class='pagination pagination-sm' >
                <li>
                  <a href='#'>«</a>
                </li>
                <li class='active'>
                  <a href='#'>1</a>
                </li>
                <li>
                  <a href='#'>2</a>
                </li>
                <li>
                  <a href='#'>3</a>
                </li>
                <li>
                  <a href='#'>4</a>
                </li>
                <li>
                  <a href='#'>5</a>
                </li>
                <li>
                  <a href='#'>6</a>
                </li>
                <li>
                  <a href='#'>7</a>
                </li>
                <li>
                  <a href='#'>8</a>
                </li>
                <li>
                  <a href='#'>»</a>
                </li>
              </ul>
              <div class='pull-right'>
                Showing 1 to 10 of 32 entries
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Footer -->
      <!-- Javascripts -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script><script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" type="text/javascript"></script><script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js" type="text/javascript"></script><script src="assets/javascripts/application-985b892b.js" type="text/javascript"></script>
      <!-- Google Analytics -->
      <script>
        var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
          s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>